import { ModuleStub } from '@/components/ModuleStub';

export default function StudentsPage() {
  return (
    <ModuleStub
      title="Students"
      description="Student ID equals barcode. Never auto-generated by ICOP."
      endpoint="/students"
    />
  );
}
